## DEPENDENCIES CONFIGURATIONS ##
set(MATH_FUNCTIONS_PACKAGE_NAME math_functions)
set(MATH_FUNCTIONS_PACKAGE_VERSION 0.1.0)
set(MATH_FUNCTIONS_PACKAGE_CONFIG_DIR ${INSTALL_ROOT_DIR}/${MATH_FUNCTIONS_PACKAGE_NAME}/${CMAKE_SYSTEM_NAME}/${CMAKE_SYSTEM_VERSION}/${CMAKE_BUILD_TYPE}/cmake)

list(APPEND CMAKE_PREFIX_PATH ${MATH_FUNCTIONS_PACKAGE_CONFIG_DIR})

# find_package(${MATH_FUNCTIONS_PACKAGE_NAME} ${MATH_FUNCTIONS_PACKAGE_VERSION} REQUIRED CONFIG)
find_package(math_functions REQUIRED)